version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-starter-web
    ports:
      - ${PORT:-3000}:3000
    environment:
      - PORT=3000
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:?}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: go-starter-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?}"]
      interval: 5s
      timeout: 5s
      retries: 5
