version: '3.1'

services:
  db:
    image: postgres
    container_name: ${PROJECT_NAME:?}-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    ports:
      - 5432:5432
