version: "3"

tasks:
  default:
    cmds:
      - ag -l . | entr -r task {{default "server" .CLI_ARGS}}

  server:
    deps:
      - generate
    cmds:
      - go run greeter_server/main.go {{.CLI_ARGS}}

  client:
    deps:
      - generate
    cmds:
      - go run greeter_client/main.go {{.CLI_ARGS}}

  generate:
    sources:
      - "**/*.proto"
    cmds:
      - |
        protoc --go_out=. --go_opt=paths=source_relative \
          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
          **/*.proto

  clean:
    cmds:
      - rm -rf .task/
