version: "3"

tasks:
  default:
    cmds:
      - ag -l . | entr -r task run

  run:
    deps:
      - templ
      - tailwindcss
    sources:
      - "**/*.go"
    cmds:
      - go run main.go

  templ:
    run: when_changed
    sources:
      - templates/*.templ
    cmds:
      - templ {{default "generate" .CLI_ARGS}}
    generates:
      - templates/**/*_templ.go

  tailwindcss:
    run: when_changed
    sources:
      - templates/*.templ
      - styles/tailwind.config.js
      - styles/tailwind.css
    cmds:
      - cd styles && tailwindcss -i ./tailwind.css -o ../public/css/tailwind.min.css --minify
    generates:
      - public/css/tailwind.min.css

  clean:
    cmds:
      - find . -type f -name '*_templ.go' | xargs --no-run-if-empty rm -rfv
      - rm -rfv public/css/tailwind.min.css
