version: "3"

tasks:
  server:
    deps:
      - generate
    cmds:
      - go run greeter_server/main.go

  client:
    deps:
      - generate
    cmds:
      - go run greeter_client/main.go

  generate:
    sources:
      - "**/*.proto"
    cmds:
      - |
        protoc --go_out=. --go_opt=paths=source_relative \
          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
          **/*.proto

  clean:
    cmds:
      - rm -rf .task/
